[package]
name = "dcap-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
hex = "0.4"
x509-parser = "0.15.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
time = "0.3.36"

p256 = { version = "0.13.2", optional = true }
sha2 = "0.10.8"
sha3 = "0.10.8"

[dependencies.p256_accelerated]
package = "p256"
git = "https://github.com/automata-network/RustCrypto-elliptic-curves.git"
optional = true

[features]
default = ["p256"]
accelerated = ["p256_accelerated"]
